apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will
spec:
  project: development
  source:
    repoURL: http://localhost:8181/root/test.git 
    # https://github.com/victor-chevillotte/iot-app.git for p3
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
