#  Commands :
#  vagrant up
#
#  vagrant ssh vchevillS
#  sudo k3s kubectl get nodes -o wide
#  sudo k3s kubectl get all
#  sudo k3s kubectl get ingress
#  sudo k3s kubectl describe ingress -A
#
#  https://app.requestly.io/rules/editor/edit/Headers_7qww5
#  curl 192.168.56.110
#  curl -H "Host: app1.com" 192.168.56.110
#  curl -H "Host: app3.com" 192.168.56.110
#
#  vagrant destroy -f
#

# Load .env file if it exists
if File.exists?('.env')
	File.foreach('.env') do |line|
	  key, value = line.split('=')
	  ENV[key] = value.strip if key && value
	end
  end

Vagrant.configure("2") do |config|

	config.vm.define "vchevillS" do |vchevillS|
	  vchevillS.vm.box = "bento/debian-12"
	  vchevillS.vm.hostname = "vchevillS"
	  vchevillS.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"
	  vchevillS.vm.synced_folder "./confs/", "/confs"
	  vchevillS.vm.provider "virtualbox" do |vb|
		vb.name = "vchevillS"
		vb.cpus = 4
		vb.memory = 2048
	  end
	  vchevillS.vm.provision :shell, inline: <<-SHELL
	  	export PATH=$PATH:/sbin
		sudo apt update && sudo apt install curl -qqy && sudo apt install net-tools -qqy
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-external-ip=192.168.56.110" K3S_TOKEN=#{ENV['K3S_TOKEN']} sh -s -
		k3s kubectl apply -f /confs/app-one.yaml
		k3s kubectl apply -f /confs/app-two.yaml
		k3s kubectl apply -f /confs/app-three.yaml
		k3s kubectl apply -f /confs/ingress.yaml
		mkdir ~/.kube 2> /dev/null
		export KUBECONFIG=~/.kube/config
		sudo k3s kubectl config view --raw > "$KUBECONFIG"
		chmod 600 "$KUBECONFIG"
		echo "export KUBECONFIG=~/.kube/config" >> /home/vagrant/.bashrc
		echo "updating PATH..."
		echo "export PATH=$PATH:/sbin" >> /home/vagrant/.bashrc
		source /home/vagrant/.bashrc
	  SHELL
	end
  
  end