#  Commands :
#  vagrant up
#
#  vagrant ssh vchevillS
#  sudo k3s kubectl get nodes -o wide
#  
#  ifconfig eth1
#  ip addr show eth1
#  
#  vagrant destroy -f
#

Vagrant.configure("2") do |config|

	config.vm.define "vchevillS" do |vchevillS|
	  vchevillS.vm.box = "bento/debian-12"
	  vchevillS.vm.hostname = "vchevillS"
	  vchevillS.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"
	  vchevillS.vm.provider "virtualbox" do |vb|
		vb.name = "vchevillS"
		vb.cpus = 2
		vb.memory = 1024
	  end
	  vchevillS.vm.provision :shell, inline: <<-SHELL
	  	export PATH=$PATH:/sbin
		sudo apt update && sudo apt install curl -qqy && sudo apt install net-tools -qqy
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-external-ip=192.168.56.110" K3S_TOKEN=vchevillsecret sh -s -
		export KUBECONFIG=~/.kube/config
		mkdir ~/.kube 2> /dev/null
		sudo k3s kubectl config view --raw > "$KUBECONFIG"
		chmod 600 "$KUBECONFIG"
	  SHELL
	end
  
	config.vm.define "vchevillSW" do |vchevillSW|
	  vchevillSW.vm.box = "bento/debian-12"
	  vchevillSW.vm.hostname = "vchevillSW"
	  vchevillSW.vm.network "private_network", ip: "192.168.56.111", bridge: "eth1"
	  vchevillSW.vm.provider "virtualbox" do |vb|
		vb.name = "vchevillSW"
		vb.cpus = 2
		vb.memory = 1024
	  end
	  vchevillSW.vm.provision :shell, inline: <<-SHELL
	  sudo apt update && sudo apt install curl -qqy && sudo apt install net-tools -qqy
	  curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=vchevillsecret sh -s -
	  SHELL
	end
  
  end